name: antai_flutter
description: " \"ANTaI\" is a multiplatform mobile app that encourages users of AI to be more critical about how they use AI, with the goals of increasing productive use, decreasing destructive use, and encouraging human authenticity in face of the rise of GenAI usage. "
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/lesson.png"

flutter:
  uses-material-design: true
